export const CONTROL_PANEL_HTML = `<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>OpenClaw Workbench</title>
<style>
:root{color-scheme:dark;--bg:#0d1117;--panel:#161b22;--line:#30363d;--muted:#8b949e;--text:#e6edf3;--accent:#58a6ff;--good:#3fb950;--warn:#d29922;--bad:#f85149}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% 0,#17243a 0,#0d1117 42%);color:var(--text);font:14px system-ui,-apple-system,"Segoe UI",sans-serif}header{height:64px;border-bottom:1px solid var(--line);display:flex;align-items:center;padding:0 28px;gap:14px}header strong{font-size:18px}header span{color:var(--muted)}main{max-width:1280px;margin:24px auto;padding:0 20px;display:grid;grid-template-columns:260px 1fr;gap:18px}.card{background:rgba(22,27,34,.94);border:1px solid var(--line);border-radius:12px;padding:18px;box-shadow:0 12px 36px #0003}.sidebar{display:flex;flex-direction:column;gap:14px}.eyebrow{font-size:11px;text-transform:uppercase;letter-spacing:.12em;color:var(--muted)}button,select,textarea,input{font:inherit;color:var(--text);background:#0d1117;border:1px solid var(--line);border-radius:7px;padding:9px}button{cursor:pointer;background:#21262d}button:hover{border-color:var(--accent)}button.primary{background:#1f6feb;border-color:#388bfd}button.danger{border-color:#da3633}.modes{display:grid;gap:8px}.mode.active{background:#1f6feb;border-color:#58a6ff}.status{display:flex;justify-content:space-between;margin:8px 0;color:var(--muted)}.dot{color:var(--good)}.content{display:grid;gap:14px}.toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.toolbar select{min-width:100px}.messages{min-height:390px;max-height:54vh;overflow:auto;display:flex;flex-direction:column;gap:10px}.msg{padding:12px;border-radius:9px;border:1px solid var(--line);white-space:pre-wrap;line-height:1.55}.msg.user{border-color:#235a9f;background:#10243d}.msg.assistant{background:#111820}.empty{margin:auto;color:var(--muted)}textarea{width:100%;min-height:90px;resize:vertical}.composer{display:grid;gap:9px}.row{display:flex;gap:8px;justify-content:space-between;align-items:center}.small{font-size:12px;color:var(--muted)}#error{color:var(--bad);min-height:18px}.proposal{border-left:3px solid var(--warn);padding-left:12px;white-space:pre-wrap}.hidden{display:none}@media(max-width:800px){main{grid-template-columns:1fr}.sidebar{display:grid;grid-template-columns:1fr 1fr}.sidebar .wide{grid-column:1/-1}.messages{max-height:none}}
</style></head>
<body><header><strong>OpenClaw Workbench</strong><span>本地可审计 Agent 控制台</span><span id="connection" class="small" style="margin-left:auto">未连接</span></header>
<main><aside class="sidebar"><section class="card wide"><div class="eyebrow">工作区</div><div id="root" class="small" style="margin-top:8px;word-break:break-all">等待状态</div><div class="status"><span>服务</span><span id="health" class="dot">检查中</span></div><div class="status"><span>人工复核</span><span id="reviews">-</span></div><button id="refresh">刷新状态</button></section><section class="card wide"><div class="eyebrow">模式</div><div class="modes" style="margin-top:10px"><button class="mode active" data-mode="Ask">Ask · 只读</button><button class="mode" data-mode="Plan">Plan · 多模型复核</button><button class="mode" data-mode="Code">Code · 审批后修改</button></div></section></aside>
<section class="content"><section class="card"><div class="row"><div><div class="eyebrow">当前会话</div><strong id="sessionLabel">尚未创建</strong></div><button id="newSession">新建会话</button></div><div id="messages" class="messages"><div class="empty">选择模式并新建会话，然后开始对话</div></div><div id="error"></div><form id="composer" class="composer"><textarea id="message" placeholder="输入任务，例如：请只读分析当前项目的安全风险"></textarea><div class="toolbar"><span class="small" id="modeHint">Ask 不会创建修改提案</span><span style="margin-left:auto"></span><button class="primary" type="submit">发送</button></div></form></section><section id="planCard" class="card hidden"><div class="row"><div><div class="eyebrow">Plan 复核</div><strong>独立模型分支</strong></div><button id="runPlan">开始复核</button></div><textarea id="planQuestion" placeholder="输入需要多模型复核的问题"></textarea><div id="planResult" class="small" style="margin-top:10px"></div></section><section id="proposalCard" class="card hidden"><div class="row"><div><div class="eyebrow">待审批提案</div><strong>执行前必须人工批准</strong></div><button id="approve" class="primary">批准执行</button></div><div id="proposal" class="proposal" style="margin-top:10px"></div></section></section></main>
<script>
const state={session:null,mode:'Ask',proposal:null}; const $=s=>document.querySelector(s); const api=async(path,opt={})=>{const r=await fetch(path,{headers:{'content-type':'application/json',...(opt.headers||{})},...opt});const b=await r.json();if(!r.ok)throw new Error(b.message||b.error||('HTTP '+r.status));return b};
function fail(e){$('#error').textContent=e.message||String(e)} function render(){document.querySelectorAll('.mode').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));$('#modeHint').textContent=state.mode==='Ask'?'Ask 不会创建修改提案':state.mode==='Plan'?'Plan 只做多模型复核，不执行修改':'Code 生成提案，执行仍需独立审批';$('#planCard').classList.toggle('hidden',state.mode!=='Plan');$('#sessionLabel').textContent=state.session?state.session.id+' · '+state.session.mode:'尚未创建';}
async function refresh(){try{const b=await api('/v1/status');$('#root').textContent=b.root;$('#health').textContent='正常';$('#reviews').textContent=(b.persistedState?.sessions?.manualReview||0)+(b.persistedState?.proposals?.manualReview||0);$('#connection').textContent='已连接';}catch(e){$('#health').textContent='异常';$('#connection').textContent='连接失败';fail(e)}}
async function loadMessages(){if(!state.session)return;const b=await api('/v1/sessions/'+state.session.id+'/messages');$('#messages').innerHTML=b.messages.length?b.messages.map(m=>'<div class="msg '+(m.role==='user'?'user':'assistant')+'"><b>'+m.role+'</b>\\n'+escapeHtml(m.content)+'</div>').join(''):'<div class="empty">暂无消息</div>';$('#messages').scrollTop=$('#messages').scrollHeight}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;render()});$('#refresh').onclick=refresh;$('#newSession').onclick=async()=>{try{state.session=(await api('/v1/sessions',{method:'POST',body:JSON.stringify({mode:state.mode,actor:'control-panel'})})).session;render();await loadMessages()}catch(e){fail(e)}};
$('#composer').onsubmit=async e=>{e.preventDefault();if(!state.session)return fail(new Error('请先新建会话'));const text=$('#message').value.trim();if(!text)return;$('#message').value='';try{const b=await api('/v1/sessions/'+state.session.id+'/messages',{method:'POST',body:JSON.stringify({message:text})});state.session=b.session;await loadMessages()}catch(e){fail(e)}};
$('#runPlan').onclick=async()=>{if(!state.session)return fail(new Error('请先创建 Plan 会话'));try{const b=await api('/v1/sessions/'+state.session.id+'/plan',{method:'POST',body:JSON.stringify({question:$('#planQuestion').value.trim(),models:['model-a','model-b']})});$('#planResult').textContent=JSON.stringify(b.synthesis||b,null,2)}catch(e){fail(e)}};
$('#approve').onclick=async()=>{if(!state.proposal)return;try{const b=await api('/v1/proposals/'+state.proposal.action.id+'/approve',{method:'POST',headers:{'x-approval-token':prompt('输入审批令牌（不会保存）')||''},body:JSON.stringify({actionHash:state.proposal.action.actionHash})});$('#proposal').textContent=JSON.stringify(b,null,2);$('#approve').disabled=true}catch(e){fail(e)}};refresh();render();
</script></body></html>`;
